# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: build and publish release to npm

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options:
          - patch
          - minor
          - major
        description: "version type, can be 'patch', 'minor', 'major'"
        required: true
        default: patch

jobs:
  npm_release:
    name: "Build and publish to npm"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.7
          run_install: |
            - args: []
      - run: pnpm jest
      - run: pnpm build
      - name: Automated Version ${{ github.event.inputs.release_type || 'patch' }}
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: "main"
          default: ${{ github.event.inputs.release_type || 'patch' }}
          commit-message: "CI: bumps version to {{version}}"
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-template: "- {title} ← {hash}"
          template: |
            ### Changelog

            {commits}

            Full changelog: {range}

            finds me on npm: https://www.npmjs.com/package/dotenv-guards

            ### Installation:
            npm: `npm install dotenv-guards@latest`
            yarn: `yarn add dotenv-guards@latest`
            pnpm: `pnpm add dotenv-guards@latest`

            made with ❤ from Vitali Haradkou
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.npm_token }}
